### ISSUE TITLE
Support single node? Also error varies if python 2 or 3

### ISSUE THREAD

**Issue by BryanQuigley** [sosreport/sos-collector#10]
Testing on Fedora 29.

Can I just have it run on localhost only for testing purposes?  It also varies in error if using python2 or python3.   (These are the same issues I was running into for Issue #2 but thought I was doing something wrong with the class)

$ python sos-collector --nodes localhost
...
Could not determine a cluster type and no list of nodes or master node was provided.
Aborting...

$ python3 sos-collector --nodes localhost
...
Unable to determine local installation. Use the --no-local option if localhost should not be included.
Aborting...

Thanks!

**Comment by TurboTurtle** [comment]
So the python3 error is a bug, which should be handled by 69e481e.

As for running a local-only test, you'd need to specify a cluster type to get past the cluster type discovery, e.g.:
`sos-collector --cluster-type=kubernetes`

You'll get an error from the cluster profile saying we couldn't find any nodes, but it should then continue with just your localhost:

```
[root@terra sos-collector]$ sos-collector --cluster-type=kubernetes
[...]
kubernetes failed to enumerate nodes: Node enumeration did not return usable output

The following is a list of nodes to collect from:
	                 
	terra.tsector.net
```

One thing to note - I'd not considered non-root, local-only runs since local-only kind of defeats the purpose of the tool, so you'd need to run sos-collector as root to get a successful run, or alternatively specify an `ssh-user` to trigger the sudo password prompt.

**Comment by BryanQuigley** [comment]
Yea, non-root local-only makes no sense..   I mostly just didn't realize a --cluster-type was required.. 

Thanks!
